package main

import (
	"gopkg.in/alecthomas/kingpin.v2"
	"os"
)

// Note: cmd tool need to use the macro definition in main.go.
// So we can not move cmd to a separate package.

type cmdMap map[string] func() error

// Run the cmd tool
func Run() error {
	appCmd := kingpin.New("MesaTracer", "MesaTracer is a command line tool used to analyze trace from " +
		"glmark2 and mesa generated by libMesaTracer.so.")
	cmds := make(cmdMap)

	stackCmd := appCmd.Command("stack", "Reconstruct the call stack from trace.")
	stackInFile := appCmd.Flag("input", "Input trace file.").Short('i').Default(defaultOutFile).String()
	stackOutFile := appCmd.Flag("output", "Out stack file.").Short('o').String()
	cmds[stackCmd.FullCommand()] = func() error {
		return cmdStack(*stackInFile, *stackOutFile)
	}

	cmd := kingpin.MustParse(appCmd.Parse(os.Args[1:]))
	for key, value := range cmds {
		if key == cmd {
			return value()
		}
	}
	return nil
}


