package main

import (
	"gopkg.in/alecthomas/kingpin.v2"
	"os"
)

// Note: cmd tool need to use the macro definition in main.go.
// So we can not move cmd to a separate package.

type cmdMap map[string] func() error

// Run the cmd tool
func Run() error {
	appCmd := kingpin.New("MesaTracer", "MesaTracer is a command line tool used to analyze trace from " +
		"glmark2 and mesa generated by libMesaTracer.so.")
	cmds := make(cmdMap)

	stackCmd := appCmd.Command("stack", "Reconstruct the call stack from trace.")
	stackInFile := stackCmd.Flag("input", "Input trace file.").Short('i').Default(defaultOutFile).String()
	stackOutFile := stackCmd.Flag("output", "Out stack file.").Short('o').String()
	cmds[stackCmd.FullCommand()] = func() error {
		return cmdStack(*stackInFile, *stackOutFile)
	}

	statisticCmd := appCmd.Command("statistic", "Statistics average duration for different calls.")
	statisticInFile := statisticCmd.Flag("input", "Input trace file.").Short('i').Default(defaultOutFile).String()
	statisticOutFile := statisticCmd.Flag("output", "Out statistic result.").Short('o').String()
	cmds[statisticCmd.FullCommand()] = func() error {
		return cmdStatistic(*statisticInFile, *statisticOutFile)
	}

	filterCmd := appCmd.Command("filter", "Filter the raw trace.")
	filterInFile := filterCmd.Flag("input", "Input trace file.").Short('i').Default(defaultOutFile).String()
	filterOutFile := filterCmd.Flag("output", "Out filtered trace file").Short('o').String()
	cmds[filterCmd.FullCommand()] = func() error {
		return cmdFilter(*filterInFile, *filterOutFile)
	}

	translateCmd := appCmd.Command("translate", "Translate flags into names.")
	transInFile := translateCmd.Flag("input", "Input trace file.").Short('i').Default(defaultOutFile).String()
	transOutFile := translateCmd.Flag("output", "Out filtered trace file").Short('o').String()
	cmds[translateCmd.FullCommand()] = func() error {
		return cmdTranslate(*transInFile, *transOutFile)
	}

	cmd := kingpin.MustParse(appCmd.Parse(os.Args[1:]))
	for key, value := range cmds {
		if key == cmd {
			return value()
		}
	}
	return nil
}


