package main
/*
#define CGO_START 0
#define CGO_END 1
#define GLM2_DRAW_BEGIN 2
#define GLM2_DRAW_END 3
#define GLM2_STEP_BEGIN 4
#define GLM2_STEP_END 5
#define GLM2_UPDATE_BEGIN 6
#define GLM2_UPDATE_END 7
#define ZINK_DRAW_BEGIN 8
#define ZINK_DRAW_END 9
#define MESA_SET_DRAW_VAO_BEGIN 10
#define MESA_SET_DRAW_VAO_END 11
#define FLUSH_FOR_DRAW_BEGIN 12
#define FLUSH_FOR_DRAW_END 13
#define MESA_DRAW_ARRAYS_BEGIN 14
#define MESA_DRAW_ARRAYS_END 15
#define ST_DRAW_VBO_BEGIN 16
#define ST_DRAW_VBO_END 17
#define ST_PREPARE_DRAW_BEGIN 18
#define ST_PREPARE_DRAW_END 19
#define CSO_DRAW_VBO_BEGIN 20
#define CSO_DRAW_VBO_END 21
#define GLM2_BUILD_RENDER_VBO_BEGIN 22
#define GLM2_BUILD_RENDER_VBO_END 23
#define GLM2_BUILD_RENDER_ARRAY_BEGIN 24
#define GLM2_BUILD_RENDER_ARRAY_END 25
#define GLM2_BUILD_LOAD_PROJECTION_BEGIN 26
#define GLM2_BUILD_LOAD_PROJECTION_END 27
#define GLM2_BUILD_LOAD_NORMAL_BEGIN 28
#define GLM2_BUILD_LOAD_NORMAL_END 29
#define GLX_SWAP_BUFFERS_BEGIN 30
#define GLX_SWAP_BUFFERS_END 31
#define GLX_DRI3_FLUSH_DRIAWABLE_BEGIN 32
#define GLX_DRI3_FLUSH_DRIAWABLE_END 33
#define ST_FLUSH_BEGIN 34
#define ST_FLUSH_END 35
#define GAL_TC_FLUSH_BEGIN 36
#define GAL_TC_FLUSH_END 37
#define GAL_DRI_FLUSH_BEGIN 38
#define GAL_DRI_FLUSH_END 39
#define GAL_DRI_THRO_PRE_BEGIN 40
#define GAL_DRI_THRO_PRE_END 41
#define MESA_CLEAR_BEGIN 42
#define MESA_CLEAR_END 43
#define MESA_CREATE_VAO_BEGIN 44
#define MESA_CREATE_VAO_END 45
#define MESA_GEN_VAO_BEGIN 46
#define MESA_GEN_VAO_END 47
#define MESA_BIND_VAO_BEGIN 48
#define MESA_BIND_VAO_END 49
#define MESA_GEN_VBO_BEGIN 50
#define MESA_GEN_VBO_END 51
#define MESA_CREATE_VBO_BEGIN 52
#define MESA_CREATE_VBO_END 53
#define MESA_BIND_VBO_BEGIN 54
#define MESA_BIND_VBO_END 55
#define MESA_VBO_DATA_BEGIN 56
#define MESA_VBO_DATA_END 57
#define MESA_VERTEX_ATTRIB_POINTER_BEGIN 58
#define MESA_VERTEX_ATTRIB_POINTER_END 59
#define GLM2_GLX_SWAP_BEGIN 60
#define GLM2_GLX_SWAP_END 61
#define GLM2_CANVAS_UPDATE_BEGIN 62
#define GLM2_CANVAS_UPDATE_END 63
*/
import "C"
import (
	"fmt"
	"github.com/Riften/goMesaTracer/tracer"
	"os"
	"time"
)

const defaultOutFile = "mesa_trace_raw.csv"
const totalFlag = 100

var FlagMap = make([]string, totalFlag)

func init() {
	var err error

	mesaCmdOnly := os.Getenv("MESA_TRACE_CMD_ONLY")
	if mesaCmdOnly != "" {
		tracer.GlobalTracer.OutCmdOnly = true
		fmt.Println("Cgo trace would be print out to command line only")
	} else {
		tracer.GlobalTracer.OutCmdOnly = false
		filePath := os.Getenv("MESA_TRACE_OUT")
		if filePath == "" {
			fmt.Println("No out file specified, use default out file ", defaultOutFile)
			fmt.Println("You can set the out file by os env MESA_TRACE_OUT")
			filePath = defaultOutFile
		}

		tracer.GlobalTracer.W, err = os.OpenFile(filePath, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0666)
		if err != nil {
			fmt.Println("Error when open output file: ", err.Error())
			panic(err)
		}
	}

	fmt.Println("Init flag map.")
	FlagMap[C.CGO_START] = "Trace_Start"
	FlagMap[C.CGO_END] = "Trace_End"
	FlagMap[C.GLM2_DRAW_BEGIN] = "GLM2_DRAW_BEGIN"
	FlagMap[C.GLM2_DRAW_END] = "GLM2_DRAW_END"
	FlagMap[C.GLM2_STEP_BEGIN] = "GLM2_STEP_BEGIN"
	FlagMap[C.GLM2_STEP_END] = "GLM2_STEP_END"
	FlagMap[C.GLM2_UPDATE_BEGIN] = "GLM2_UPDATE_BEGIN"
	FlagMap[C.GLM2_UPDATE_END] = "GLM2_UPDATE_END"
	FlagMap[C.ZINK_DRAW_BEGIN] = "ZINK_DRAW_BEGIN"
	FlagMap[C.ZINK_DRAW_END] = "ZINK_DRAW_END"
	FlagMap[C.MESA_SET_DRAW_VAO_BEGIN] = "MESA_SET_DRAW_VAO_BEGIN"
	FlagMap[C.MESA_SET_DRAW_VAO_END] = "MESA_SET_DRAW_VAO_END"
	FlagMap[C.FLUSH_FOR_DRAW_BEGIN] = "FLUSH_FOR_DRAW_BEGIN"
	FlagMap[C.FLUSH_FOR_DRAW_END] = "FLUSH_FOR_DRAW_END"
	FlagMap[C.MESA_DRAW_ARRAYS_BEGIN] = "MESA_DRAW_ARRAYS_BEGIN"
	FlagMap[C.MESA_DRAW_ARRAYS_END] = "MESA_DRAW_ARRAYS_END"
	FlagMap[C.ST_DRAW_VBO_BEGIN] = "ST_DRAW_VBO_BEGIN"
	FlagMap[C.ST_DRAW_VBO_END] = "ST_DRAW_VBO_END"
	FlagMap[C.ST_PREPARE_DRAW_BEGIN] = "ST_PREPARE_DRAW_BEGIN"
	FlagMap[C.ST_PREPARE_DRAW_END] = "ST_PREPARE_DRAW_END"
	FlagMap[C.CSO_DRAW_VBO_BEGIN] = "CSO_DRAW_VBO_BEGIN"
	FlagMap[C.CSO_DRAW_VBO_END] = "CSO_DRAW_VBO_END"
	FlagMap[C.GLM2_BUILD_RENDER_VBO_BEGIN] = "GLM2_BUILD_RENDER_VBO_BEGIN"
	FlagMap[C.GLM2_BUILD_RENDER_VBO_END] = "GLM2_BUILD_RENDER_VBO_END"
	FlagMap[C.GLM2_BUILD_RENDER_ARRAY_BEGIN] = "GLM2_BUILD_RENDER_ARRAY_BEGIN"
	FlagMap[C.GLM2_BUILD_RENDER_ARRAY_END] = "GLM2_BUILD_RENDER_ARRAY_END"
	FlagMap[C.GLM2_BUILD_LOAD_PROJECTION_BEGIN] = "GLM2_BUILD_LOAD_PROJECTION_BEGIN"
	FlagMap[C.GLM2_BUILD_LOAD_PROJECTION_END] = "GLM2_BUILD_LOAD_PROJECTION_END"
	FlagMap[C.GLM2_BUILD_LOAD_NORMAL_BEGIN] = "GLM2_BUILD_LOAD_NORMAL_BEGIN"
	FlagMap[C.GLM2_BUILD_LOAD_NORMAL_END] = "GLM2_BUILD_LOAD_NORMAL_END"
	FlagMap[C.GLX_SWAP_BUFFERS_BEGIN] = "GLX_SWAP_BUFFERS_BEGIN"
	FlagMap[C.GLX_SWAP_BUFFERS_END] = "GLX_SWAP_BUFFERS_END"
	FlagMap[C.GLX_DRI3_FLUSH_DRIAWABLE_BEGIN] = "GLX_DRI3_FLUSH_DRIAWABLE_BEGIN"
	FlagMap[C.GLX_DRI3_FLUSH_DRIAWABLE_END] = "GLX_DRI3_FLUSH_DRIAWABLE_END"
	FlagMap[C.ST_FLUSH_BEGIN] = "ST_FLUSH_BEGIN"
	FlagMap[C.ST_FLUSH_END] = "ST_FLUSH_END"
	FlagMap[C.GAL_TC_FLUSH_BEGIN] = "GAL_TC_FLUSH_BEGIN"
	FlagMap[C.GAL_TC_FLUSH_END] = "GAL_TC_FLUSH_END"
	FlagMap[C.GAL_DRI_FLUSH_BEGIN] = "GAL_DRI_FLUSH_BEGIN"
	FlagMap[C.GAL_DRI_FLUSH_END] = "GAL_DRI_FLUSH_END"
	FlagMap[C.GAL_DRI_THRO_PRE_BEGIN] = "GAL_DRI_THRO_PRE_BEGIN"
	FlagMap[C.GAL_DRI_THRO_PRE_END] = "GAL_DRI_THRO_PRE_END"
	FlagMap[C.MESA_CLEAR_BEGIN] = "MESA_CLEAR_BEGIN"
	FlagMap[C.MESA_CLEAR_END] = "MESA_CLEAR_END"
	FlagMap[C.MESA_CREATE_VAO_BEGIN] = "MESA_CREATE_VAO_BEGIN"
	FlagMap[C.MESA_CREATE_VAO_END] = "MESA_CREATE_VAO_END"
	FlagMap[C.MESA_GEN_VAO_BEGIN] = "MESA_GEN_VAO_BEGIN"
	FlagMap[C.MESA_GEN_VAO_END]= "MESA_GEN_VAO_END"
	FlagMap[C.MESA_BIND_VAO_BEGIN] = "MESA_BIND_VAO_BEGIN"
	FlagMap[C.MESA_BIND_VAO_END] = "MESA_BIND_VAO_END"
	FlagMap[C.MESA_GEN_VBO_BEGIN] = "MESA_GEN_VBO_BEGIN"
	FlagMap[C.MESA_GEN_VBO_END] = "MESA_GEN_VBO_END"
	FlagMap[C.MESA_CREATE_VBO_BEGIN] = "MESA_CREATE_VBO_BEGIN"
	FlagMap[C.MESA_CREATE_VBO_END] = "MESA_CREATE_VBO_END"
	FlagMap[C.MESA_BIND_VBO_BEGIN] = "MESA_BIND_VBO_BEGIN"
	FlagMap[C.MESA_BIND_VBO_END] = "MESA_BIND_VBO_END"
	FlagMap[C.MESA_VBO_DATA_BEGIN] = "MESA_VBO_DATA_BEGIN"
	FlagMap[C.MESA_VBO_DATA_END] = "MESA_VBO_DATA_END"
	FlagMap[C.MESA_VERTEX_ATTRIB_POINTER_BEGIN] = "MESA_VERTEX_ATTRIB_POINTER_BEGIN"
	FlagMap[C.MESA_VERTEX_ATTRIB_POINTER_END] = "MESA_VERTEX_ATTRIB_POINTER_END"
	FlagMap[C.GLM2_GLX_SWAP_BEGIN] = "GLM2_GLX_SWAP_BEGIN"
	FlagMap[C.GLM2_GLX_SWAP_END] = "GLM2_GLX_SWAP_END"
	FlagMap[C.GLM2_CANVAS_UPDATE_BEGIN] = "GLM2_CANVAS_UPDATE_BEGIN"
	FlagMap[C.GLM2_CANVAS_UPDATE_END] = "GLM2_CANVAS_UPDATE_END"

	tracer.GlobalTracer.FetchFlagName = func(cgoType int) string {
		return FlagMap[cgoType]
	}
	fmt.Println("Initialize main routine")
	go tracer.GlobalTracer.Start()
}

//export cgoAddTrace
func cgoAddTrace(cgoType C.int) {
	tracer.GlobalTracer.AddRecord(int(cgoType))
}

//export cgoStopAndWait
func cgoStopAndWait() {
	// TODO: End the writer routine and write back logs
	tracer.GlobalTracer.End()
	time.Sleep(2 * time.Second) // wait for 2 minute
	return
}

func main() {
	err := Run()
	if err != nil {
		fmt.Println("Error in cmd: ", err)
	}
	return
}
